// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMulaiDay6Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView hari699;

  @NonNull
  public final ImageView imageView699;

  @NonNull
  public final TextView senam;

  @NonNull
  public final Button startButton699;

  @NonNull
  public final TextView timerTextView699;

  @NonNull
  public final TextView titleQuestion699;

  private ActivityMulaiDay6Binding(@NonNull LinearLayout rootView, @NonNull TextView hari699,
      @NonNull ImageView imageView699, @NonNull TextView senam, @NonNull Button startButton699,
      @NonNull TextView timerTextView699, @NonNull TextView titleQuestion699) {
    this.rootView = rootView;
    this.hari699 = hari699;
    this.imageView699 = imageView699;
    this.senam = senam;
    this.startButton699 = startButton699;
    this.timerTextView699 = timerTextView699;
    this.titleQuestion699 = titleQuestion699;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMulaiDay6Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMulaiDay6Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mulai_day6, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMulaiDay6Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.hari699;
      TextView hari699 = ViewBindings.findChildViewById(rootView, id);
      if (hari699 == null) {
        break missingId;
      }

      id = R.id.imageView699;
      ImageView imageView699 = ViewBindings.findChildViewById(rootView, id);
      if (imageView699 == null) {
        break missingId;
      }

      id = R.id.senam;
      TextView senam = ViewBindings.findChildViewById(rootView, id);
      if (senam == null) {
        break missingId;
      }

      id = R.id.startButton699;
      Button startButton699 = ViewBindings.findChildViewById(rootView, id);
      if (startButton699 == null) {
        break missingId;
      }

      id = R.id.timerTextView699;
      TextView timerTextView699 = ViewBindings.findChildViewById(rootView, id);
      if (timerTextView699 == null) {
        break missingId;
      }

      id = R.id.title_question699;
      TextView titleQuestion699 = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion699 == null) {
        break missingId;
      }

      return new ActivityMulaiDay6Binding((LinearLayout) rootView, hari699, imageView699, senam,
          startButton699, timerTextView699, titleQuestion699);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
