// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMulaiDay3Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView hari3;

  @NonNull
  public final ImageView imageView3;

  @NonNull
  public final Button startButton3;

  @NonNull
  public final TextView strecing;

  @NonNull
  public final TextView timerTextView3;

  @NonNull
  public final TextView titleQuestion3;

  private ActivityMulaiDay3Binding(@NonNull LinearLayout rootView, @NonNull TextView hari3,
      @NonNull ImageView imageView3, @NonNull Button startButton3, @NonNull TextView strecing,
      @NonNull TextView timerTextView3, @NonNull TextView titleQuestion3) {
    this.rootView = rootView;
    this.hari3 = hari3;
    this.imageView3 = imageView3;
    this.startButton3 = startButton3;
    this.strecing = strecing;
    this.timerTextView3 = timerTextView3;
    this.titleQuestion3 = titleQuestion3;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMulaiDay3Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMulaiDay3Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mulai_day3, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMulaiDay3Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.hari3;
      TextView hari3 = ViewBindings.findChildViewById(rootView, id);
      if (hari3 == null) {
        break missingId;
      }

      id = R.id.imageView3;
      ImageView imageView3 = ViewBindings.findChildViewById(rootView, id);
      if (imageView3 == null) {
        break missingId;
      }

      id = R.id.startButton3;
      Button startButton3 = ViewBindings.findChildViewById(rootView, id);
      if (startButton3 == null) {
        break missingId;
      }

      id = R.id.strecing;
      TextView strecing = ViewBindings.findChildViewById(rootView, id);
      if (strecing == null) {
        break missingId;
      }

      id = R.id.timerTextView3;
      TextView timerTextView3 = ViewBindings.findChildViewById(rootView, id);
      if (timerTextView3 == null) {
        break missingId;
      }

      id = R.id.title_question3;
      TextView titleQuestion3 = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion3 == null) {
        break missingId;
      }

      return new ActivityMulaiDay3Binding((LinearLayout) rootView, hari3, imageView3, startButton3,
          strecing, timerTextView3, titleQuestion3);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
