// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityPushupmaleBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button21;

  @NonNull
  public final Button button22;

  @NonNull
  public final Button button23;

  @NonNull
  public final Button button24;

  @NonNull
  public final Button button25;

  @NonNull
  public final ImageView imageView9;

  @NonNull
  public final LinearLayout main;

  private ActivityPushupmaleBinding(@NonNull LinearLayout rootView, @NonNull Button button21,
      @NonNull Button button22, @NonNull Button button23, @NonNull Button button24,
      @NonNull Button button25, @NonNull ImageView imageView9, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.button21 = button21;
    this.button22 = button22;
    this.button23 = button23;
    this.button24 = button24;
    this.button25 = button25;
    this.imageView9 = imageView9;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityPushupmaleBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityPushupmaleBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_pushupmale, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityPushupmaleBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button21;
      Button button21 = ViewBindings.findChildViewById(rootView, id);
      if (button21 == null) {
        break missingId;
      }

      id = R.id.button22;
      Button button22 = ViewBindings.findChildViewById(rootView, id);
      if (button22 == null) {
        break missingId;
      }

      id = R.id.button23;
      Button button23 = ViewBindings.findChildViewById(rootView, id);
      if (button23 == null) {
        break missingId;
      }

      id = R.id.button24;
      Button button24 = ViewBindings.findChildViewById(rootView, id);
      if (button24 == null) {
        break missingId;
      }

      id = R.id.button25;
      Button button25 = ViewBindings.findChildViewById(rootView, id);
      if (button25 == null) {
        break missingId;
      }

      id = R.id.imageView9;
      ImageView imageView9 = ViewBindings.findChildViewById(rootView, id);
      if (imageView9 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityPushupmaleBinding((LinearLayout) rootView, button21, button22, button23,
          button24, button25, imageView9, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
