// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityBeratbadanBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView bmiTextView;

  @NonNull
  public final Button button5;

  @NonNull
  public final ImageView imageView9;

  @NonNull
  public final RadioButton kgButton;

  @NonNull
  public final RadioButton lbButton;

  @NonNull
  public final LinearLayout main;

  @NonNull
  public final TextView titleQuestion;

  @NonNull
  public final RadioGroup unitGroup;

  @NonNull
  public final SeekBar weightSeekBar;

  @NonNull
  public final TextView weightTextView;

  private ActivityBeratbadanBinding(@NonNull LinearLayout rootView, @NonNull TextView bmiTextView,
      @NonNull Button button5, @NonNull ImageView imageView9, @NonNull RadioButton kgButton,
      @NonNull RadioButton lbButton, @NonNull LinearLayout main, @NonNull TextView titleQuestion,
      @NonNull RadioGroup unitGroup, @NonNull SeekBar weightSeekBar,
      @NonNull TextView weightTextView) {
    this.rootView = rootView;
    this.bmiTextView = bmiTextView;
    this.button5 = button5;
    this.imageView9 = imageView9;
    this.kgButton = kgButton;
    this.lbButton = lbButton;
    this.main = main;
    this.titleQuestion = titleQuestion;
    this.unitGroup = unitGroup;
    this.weightSeekBar = weightSeekBar;
    this.weightTextView = weightTextView;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBeratbadanBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBeratbadanBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_beratbadan, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBeratbadanBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bmiTextView;
      TextView bmiTextView = ViewBindings.findChildViewById(rootView, id);
      if (bmiTextView == null) {
        break missingId;
      }

      id = R.id.button5;
      Button button5 = ViewBindings.findChildViewById(rootView, id);
      if (button5 == null) {
        break missingId;
      }

      id = R.id.imageView9;
      ImageView imageView9 = ViewBindings.findChildViewById(rootView, id);
      if (imageView9 == null) {
        break missingId;
      }

      id = R.id.kgButton;
      RadioButton kgButton = ViewBindings.findChildViewById(rootView, id);
      if (kgButton == null) {
        break missingId;
      }

      id = R.id.lbButton;
      RadioButton lbButton = ViewBindings.findChildViewById(rootView, id);
      if (lbButton == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      id = R.id.title_question;
      TextView titleQuestion = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion == null) {
        break missingId;
      }

      id = R.id.unitGroup;
      RadioGroup unitGroup = ViewBindings.findChildViewById(rootView, id);
      if (unitGroup == null) {
        break missingId;
      }

      id = R.id.weightSeekBar;
      SeekBar weightSeekBar = ViewBindings.findChildViewById(rootView, id);
      if (weightSeekBar == null) {
        break missingId;
      }

      id = R.id.weightTextView;
      TextView weightTextView = ViewBindings.findChildViewById(rootView, id);
      if (weightTextView == null) {
        break missingId;
      }

      return new ActivityBeratbadanBinding((LinearLayout) rootView, bmiTextView, button5,
          imageView9, kgButton, lbButton, main, titleQuestion, unitGroup, weightSeekBar,
          weightTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
