// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button12;

  @NonNull
  public final Button button4;

  @NonNull
  public final Button button77;

  @NonNull
  public final EditText emailEditText;

  @NonNull
  public final ImageView fb;

  @NonNull
  public final ImageView google;

  @NonNull
  public final ImageView imageView4;

  @NonNull
  public final LinearLayout main;

  @NonNull
  public final EditText passwordEditText;

  @NonNull
  public final ImageView showPasswordIcon;

  @NonNull
  public final ImageView twiter;

  @NonNull
  public final TextView value;

  private ActivityMainBinding(@NonNull LinearLayout rootView, @NonNull Button button12,
      @NonNull Button button4, @NonNull Button button77, @NonNull EditText emailEditText,
      @NonNull ImageView fb, @NonNull ImageView google, @NonNull ImageView imageView4,
      @NonNull LinearLayout main, @NonNull EditText passwordEditText,
      @NonNull ImageView showPasswordIcon, @NonNull ImageView twiter, @NonNull TextView value) {
    this.rootView = rootView;
    this.button12 = button12;
    this.button4 = button4;
    this.button77 = button77;
    this.emailEditText = emailEditText;
    this.fb = fb;
    this.google = google;
    this.imageView4 = imageView4;
    this.main = main;
    this.passwordEditText = passwordEditText;
    this.showPasswordIcon = showPasswordIcon;
    this.twiter = twiter;
    this.value = value;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button12;
      Button button12 = ViewBindings.findChildViewById(rootView, id);
      if (button12 == null) {
        break missingId;
      }

      id = R.id.button4;
      Button button4 = ViewBindings.findChildViewById(rootView, id);
      if (button4 == null) {
        break missingId;
      }

      id = R.id.button77;
      Button button77 = ViewBindings.findChildViewById(rootView, id);
      if (button77 == null) {
        break missingId;
      }

      id = R.id.emailEditText;
      EditText emailEditText = ViewBindings.findChildViewById(rootView, id);
      if (emailEditText == null) {
        break missingId;
      }

      id = R.id.fb;
      ImageView fb = ViewBindings.findChildViewById(rootView, id);
      if (fb == null) {
        break missingId;
      }

      id = R.id.google;
      ImageView google = ViewBindings.findChildViewById(rootView, id);
      if (google == null) {
        break missingId;
      }

      id = R.id.imageView4;
      ImageView imageView4 = ViewBindings.findChildViewById(rootView, id);
      if (imageView4 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      id = R.id.passwordEditText;
      EditText passwordEditText = ViewBindings.findChildViewById(rootView, id);
      if (passwordEditText == null) {
        break missingId;
      }

      id = R.id.showPasswordIcon;
      ImageView showPasswordIcon = ViewBindings.findChildViewById(rootView, id);
      if (showPasswordIcon == null) {
        break missingId;
      }

      id = R.id.twiter;
      ImageView twiter = ViewBindings.findChildViewById(rootView, id);
      if (twiter == null) {
        break missingId;
      }

      id = R.id.value;
      TextView value = ViewBindings.findChildViewById(rootView, id);
      if (value == null) {
        break missingId;
      }

      return new ActivityMainBinding((LinearLayout) rootView, button12, button4, button77,
          emailEditText, fb, google, imageView4, main, passwordEditText, showPasswordIcon, twiter,
          value);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
