// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityInDay1Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button19;

  @NonNull
  public final Button button20;

  @NonNull
  public final Button button26;

  @NonNull
  public final Button button6;

  @NonNull
  public final Button button8;

  @NonNull
  public final ImageView imageViewinDay1;

  @NonNull
  public final LinearLayout main;

  private ActivityInDay1Binding(@NonNull LinearLayout rootView, @NonNull Button button19,
      @NonNull Button button20, @NonNull Button button26, @NonNull Button button6,
      @NonNull Button button8, @NonNull ImageView imageViewinDay1, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.button19 = button19;
    this.button20 = button20;
    this.button26 = button26;
    this.button6 = button6;
    this.button8 = button8;
    this.imageViewinDay1 = imageViewinDay1;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityInDay1Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityInDay1Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_in_day1, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityInDay1Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button19;
      Button button19 = ViewBindings.findChildViewById(rootView, id);
      if (button19 == null) {
        break missingId;
      }

      id = R.id.button20;
      Button button20 = ViewBindings.findChildViewById(rootView, id);
      if (button20 == null) {
        break missingId;
      }

      id = R.id.button26;
      Button button26 = ViewBindings.findChildViewById(rootView, id);
      if (button26 == null) {
        break missingId;
      }

      id = R.id.button6;
      Button button6 = ViewBindings.findChildViewById(rootView, id);
      if (button6 == null) {
        break missingId;
      }

      id = R.id.button8;
      Button button8 = ViewBindings.findChildViewById(rootView, id);
      if (button8 == null) {
        break missingId;
      }

      id = R.id.imageViewinDay1;
      ImageView imageViewinDay1 = ViewBindings.findChildViewById(rootView, id);
      if (imageViewinDay1 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityInDay1Binding((LinearLayout) rootView, button19, button20, button26,
          button6, button8, imageViewinDay1, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
