// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityInDay2Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button27;

  @NonNull
  public final Button button28;

  @NonNull
  public final Button button29;

  @NonNull
  public final Button button30;

  @NonNull
  public final Button button31;

  @NonNull
  public final ImageView imageViewinDay1;

  @NonNull
  public final LinearLayout main;

  private ActivityInDay2Binding(@NonNull LinearLayout rootView, @NonNull Button button27,
      @NonNull Button button28, @NonNull Button button29, @NonNull Button button30,
      @NonNull Button button31, @NonNull ImageView imageViewinDay1, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.button27 = button27;
    this.button28 = button28;
    this.button29 = button29;
    this.button30 = button30;
    this.button31 = button31;
    this.imageViewinDay1 = imageViewinDay1;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityInDay2Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityInDay2Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_in_day2, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityInDay2Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button27;
      Button button27 = ViewBindings.findChildViewById(rootView, id);
      if (button27 == null) {
        break missingId;
      }

      id = R.id.button28;
      Button button28 = ViewBindings.findChildViewById(rootView, id);
      if (button28 == null) {
        break missingId;
      }

      id = R.id.button29;
      Button button29 = ViewBindings.findChildViewById(rootView, id);
      if (button29 == null) {
        break missingId;
      }

      id = R.id.button30;
      Button button30 = ViewBindings.findChildViewById(rootView, id);
      if (button30 == null) {
        break missingId;
      }

      id = R.id.button31;
      Button button31 = ViewBindings.findChildViewById(rootView, id);
      if (button31 == null) {
        break missingId;
      }

      id = R.id.imageViewinDay1;
      ImageView imageViewinDay1 = ViewBindings.findChildViewById(rootView, id);
      if (imageViewinDay1 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityInDay2Binding((LinearLayout) rootView, button27, button28, button29,
          button30, button31, imageViewinDay1, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
