// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityInDay4Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button37;

  @NonNull
  public final Button button38;

  @NonNull
  public final Button button39;

  @NonNull
  public final Button button40;

  @NonNull
  public final Button button41;

  @NonNull
  public final ImageView imageViewinDay1;

  @NonNull
  public final LinearLayout main;

  private ActivityInDay4Binding(@NonNull LinearLayout rootView, @NonNull Button button37,
      @NonNull Button button38, @NonNull Button button39, @NonNull Button button40,
      @NonNull Button button41, @NonNull ImageView imageViewinDay1, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.button37 = button37;
    this.button38 = button38;
    this.button39 = button39;
    this.button40 = button40;
    this.button41 = button41;
    this.imageViewinDay1 = imageViewinDay1;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityInDay4Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityInDay4Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_in_day4, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityInDay4Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button37;
      Button button37 = ViewBindings.findChildViewById(rootView, id);
      if (button37 == null) {
        break missingId;
      }

      id = R.id.button38;
      Button button38 = ViewBindings.findChildViewById(rootView, id);
      if (button38 == null) {
        break missingId;
      }

      id = R.id.button39;
      Button button39 = ViewBindings.findChildViewById(rootView, id);
      if (button39 == null) {
        break missingId;
      }

      id = R.id.button40;
      Button button40 = ViewBindings.findChildViewById(rootView, id);
      if (button40 == null) {
        break missingId;
      }

      id = R.id.button41;
      Button button41 = ViewBindings.findChildViewById(rootView, id);
      if (button41 == null) {
        break missingId;
      }

      id = R.id.imageViewinDay1;
      ImageView imageViewinDay1 = ViewBindings.findChildViewById(rootView, id);
      if (imageViewinDay1 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityInDay4Binding((LinearLayout) rootView, button37, button38, button39,
          button40, button41, imageViewinDay1, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
