// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityQuestiontinggibadanBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button buttonNext;

  @NonNull
  public final ImageView imageView9;

  @NonNull
  public final RadioButton radioCm;

  @NonNull
  public final RadioButton radioFt;

  @NonNull
  public final RadioGroup radioGroupUnit;

  @NonNull
  public final SeekBar seekBarHeight;

  @NonNull
  public final TextView titleQuestion;

  @NonNull
  public final TextView tvHeight;

  @NonNull
  public final TextView tvUnit;

  private ActivityQuestiontinggibadanBinding(@NonNull LinearLayout rootView,
      @NonNull Button buttonNext, @NonNull ImageView imageView9, @NonNull RadioButton radioCm,
      @NonNull RadioButton radioFt, @NonNull RadioGroup radioGroupUnit,
      @NonNull SeekBar seekBarHeight, @NonNull TextView titleQuestion, @NonNull TextView tvHeight,
      @NonNull TextView tvUnit) {
    this.rootView = rootView;
    this.buttonNext = buttonNext;
    this.imageView9 = imageView9;
    this.radioCm = radioCm;
    this.radioFt = radioFt;
    this.radioGroupUnit = radioGroupUnit;
    this.seekBarHeight = seekBarHeight;
    this.titleQuestion = titleQuestion;
    this.tvHeight = tvHeight;
    this.tvUnit = tvUnit;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityQuestiontinggibadanBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityQuestiontinggibadanBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_questiontinggibadan, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityQuestiontinggibadanBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button_next;
      Button buttonNext = ViewBindings.findChildViewById(rootView, id);
      if (buttonNext == null) {
        break missingId;
      }

      id = R.id.imageView9;
      ImageView imageView9 = ViewBindings.findChildViewById(rootView, id);
      if (imageView9 == null) {
        break missingId;
      }

      id = R.id.radio_cm;
      RadioButton radioCm = ViewBindings.findChildViewById(rootView, id);
      if (radioCm == null) {
        break missingId;
      }

      id = R.id.radio_ft;
      RadioButton radioFt = ViewBindings.findChildViewById(rootView, id);
      if (radioFt == null) {
        break missingId;
      }

      id = R.id.radioGroupUnit;
      RadioGroup radioGroupUnit = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupUnit == null) {
        break missingId;
      }

      id = R.id.seekBarHeight;
      SeekBar seekBarHeight = ViewBindings.findChildViewById(rootView, id);
      if (seekBarHeight == null) {
        break missingId;
      }

      id = R.id.title_question;
      TextView titleQuestion = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion == null) {
        break missingId;
      }

      id = R.id.tv_height;
      TextView tvHeight = ViewBindings.findChildViewById(rootView, id);
      if (tvHeight == null) {
        break missingId;
      }

      id = R.id.tv_unit;
      TextView tvUnit = ViewBindings.findChildViewById(rootView, id);
      if (tvUnit == null) {
        break missingId;
      }

      return new ActivityQuestiontinggibadanBinding((LinearLayout) rootView, buttonNext, imageView9,
          radioCm, radioFt, radioGroupUnit, seekBarHeight, titleQuestion, tvHeight, tvUnit);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
