// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMulaiDay2Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView hari2;

  @NonNull
  public final ImageView imageView9;

  @NonNull
  public final TextView squat;

  @NonNull
  public final Button startButton2;

  @NonNull
  public final TextView timerTextView2;

  @NonNull
  public final TextView titleQuestion2;

  private ActivityMulaiDay2Binding(@NonNull LinearLayout rootView, @NonNull TextView hari2,
      @NonNull ImageView imageView9, @NonNull TextView squat, @NonNull Button startButton2,
      @NonNull TextView timerTextView2, @NonNull TextView titleQuestion2) {
    this.rootView = rootView;
    this.hari2 = hari2;
    this.imageView9 = imageView9;
    this.squat = squat;
    this.startButton2 = startButton2;
    this.timerTextView2 = timerTextView2;
    this.titleQuestion2 = titleQuestion2;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMulaiDay2Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMulaiDay2Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mulai_day2, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMulaiDay2Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.hari2;
      TextView hari2 = ViewBindings.findChildViewById(rootView, id);
      if (hari2 == null) {
        break missingId;
      }

      id = R.id.imageView9;
      ImageView imageView9 = ViewBindings.findChildViewById(rootView, id);
      if (imageView9 == null) {
        break missingId;
      }

      id = R.id.squat;
      TextView squat = ViewBindings.findChildViewById(rootView, id);
      if (squat == null) {
        break missingId;
      }

      id = R.id.startButton2;
      Button startButton2 = ViewBindings.findChildViewById(rootView, id);
      if (startButton2 == null) {
        break missingId;
      }

      id = R.id.timerTextView2;
      TextView timerTextView2 = ViewBindings.findChildViewById(rootView, id);
      if (timerTextView2 == null) {
        break missingId;
      }

      id = R.id.title_question2;
      TextView titleQuestion2 = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion2 == null) {
        break missingId;
      }

      return new ActivityMulaiDay2Binding((LinearLayout) rootView, hari2, imageView9, squat,
          startButton2, timerTextView2, titleQuestion2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
