// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityJoggingHistoryBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button clearHistoryButton;

  @NonNull
  public final ListView historyListView;

  @NonNull
  public final TextView historyTitle;

  private ActivityJoggingHistoryBinding(@NonNull LinearLayout rootView,
      @NonNull Button clearHistoryButton, @NonNull ListView historyListView,
      @NonNull TextView historyTitle) {
    this.rootView = rootView;
    this.clearHistoryButton = clearHistoryButton;
    this.historyListView = historyListView;
    this.historyTitle = historyTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityJoggingHistoryBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityJoggingHistoryBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_jogging_history, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityJoggingHistoryBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.clearHistoryButton;
      Button clearHistoryButton = ViewBindings.findChildViewById(rootView, id);
      if (clearHistoryButton == null) {
        break missingId;
      }

      id = R.id.historyListView;
      ListView historyListView = ViewBindings.findChildViewById(rootView, id);
      if (historyListView == null) {
        break missingId;
      }

      id = R.id.historyTitle;
      TextView historyTitle = ViewBindings.findChildViewById(rootView, id);
      if (historyTitle == null) {
        break missingId;
      }

      return new ActivityJoggingHistoryBinding((LinearLayout) rootView, clearHistoryButton,
          historyListView, historyTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
