// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityInDay3Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button button32;

  @NonNull
  public final Button button33;

  @NonNull
  public final Button button34;

  @NonNull
  public final Button button35;

  @NonNull
  public final Button button36;

  @NonNull
  public final ImageView imageViewinDay1;

  @NonNull
  public final LinearLayout main;

  private ActivityInDay3Binding(@NonNull LinearLayout rootView, @NonNull Button button32,
      @NonNull Button button33, @NonNull Button button34, @NonNull Button button35,
      @NonNull Button button36, @NonNull ImageView imageViewinDay1, @NonNull LinearLayout main) {
    this.rootView = rootView;
    this.button32 = button32;
    this.button33 = button33;
    this.button34 = button34;
    this.button35 = button35;
    this.button36 = button36;
    this.imageViewinDay1 = imageViewinDay1;
    this.main = main;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityInDay3Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityInDay3Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_in_day3, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityInDay3Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.button32;
      Button button32 = ViewBindings.findChildViewById(rootView, id);
      if (button32 == null) {
        break missingId;
      }

      id = R.id.button33;
      Button button33 = ViewBindings.findChildViewById(rootView, id);
      if (button33 == null) {
        break missingId;
      }

      id = R.id.button34;
      Button button34 = ViewBindings.findChildViewById(rootView, id);
      if (button34 == null) {
        break missingId;
      }

      id = R.id.button35;
      Button button35 = ViewBindings.findChildViewById(rootView, id);
      if (button35 == null) {
        break missingId;
      }

      id = R.id.button36;
      Button button36 = ViewBindings.findChildViewById(rootView, id);
      if (button36 == null) {
        break missingId;
      }

      id = R.id.imageViewinDay1;
      ImageView imageViewinDay1 = ViewBindings.findChildViewById(rootView, id);
      if (imageViewinDay1 == null) {
        break missingId;
      }

      LinearLayout main = (LinearLayout) rootView;

      return new ActivityInDay3Binding((LinearLayout) rootView, button32, button33, button34,
          button35, button36, imageViewinDay1, main);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
