// Generated by view binder compiler. Do not edit!
package com.example.coba.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.coba.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMulaiDay1Binding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final TextView hari1;

  @NonNull
  public final ImageView imageView9;

  @NonNull
  public final TextView pushUP;

  @NonNull
  public final Button startButton;

  @NonNull
  public final TextView timerTextView;

  @NonNull
  public final TextView titleQuestion;

  private ActivityMulaiDay1Binding(@NonNull LinearLayout rootView, @NonNull TextView hari1,
      @NonNull ImageView imageView9, @NonNull TextView pushUP, @NonNull Button startButton,
      @NonNull TextView timerTextView, @NonNull TextView titleQuestion) {
    this.rootView = rootView;
    this.hari1 = hari1;
    this.imageView9 = imageView9;
    this.pushUP = pushUP;
    this.startButton = startButton;
    this.timerTextView = timerTextView;
    this.titleQuestion = titleQuestion;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMulaiDay1Binding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMulaiDay1Binding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_mulai_day1, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMulaiDay1Binding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.hari1;
      TextView hari1 = ViewBindings.findChildViewById(rootView, id);
      if (hari1 == null) {
        break missingId;
      }

      id = R.id.imageView9;
      ImageView imageView9 = ViewBindings.findChildViewById(rootView, id);
      if (imageView9 == null) {
        break missingId;
      }

      id = R.id.pushUP;
      TextView pushUP = ViewBindings.findChildViewById(rootView, id);
      if (pushUP == null) {
        break missingId;
      }

      id = R.id.startButton;
      Button startButton = ViewBindings.findChildViewById(rootView, id);
      if (startButton == null) {
        break missingId;
      }

      id = R.id.timerTextView;
      TextView timerTextView = ViewBindings.findChildViewById(rootView, id);
      if (timerTextView == null) {
        break missingId;
      }

      id = R.id.title_question;
      TextView titleQuestion = ViewBindings.findChildViewById(rootView, id);
      if (titleQuestion == null) {
        break missingId;
      }

      return new ActivityMulaiDay1Binding((LinearLayout) rootView, hari1, imageView9, pushUP,
          startButton, timerTextView, titleQuestion);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
